version: "3"
services:
  db:
    image: mysql:8
    container_name: test20.db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: test20
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: test20
      TZ: UTC
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: